#Problem Statement1: Write a Python program to multiply a M×N matrix by N×A matrix and create a real matrix product.
M=5,N=3,A=2

In [28]:
import numpy as np
np.random.seed(82)
x=np.random.random((5,3))
print("First array: ")
print(x)
y=np.random.random((3,2))
print("Second array: ")
print(y)
z=np.dot(x,y)
print("Dot product of two arrays: ")
print(z)


First array: 
[[0.27522567 0.63923076 0.62389921]
 [0.77804231 0.47811353 0.95913389]
 [0.99743421 0.83251328 0.20384505]
 [0.13405    0.61501462 0.59298706]
 [0.64478049 0.98872053 0.33516261]]
Second array: 
[[0.80851882 0.67091492]
 [0.53814006 0.06950879]
 [0.08950123 0.87179229]]
Dot product of two arrays: 
[[0.62236056 0.77299569]
 [0.97219756 1.39139882]
 [1.27269746 0.90477103]
 [0.49241902 0.64964662]
 [1.08338476 0.79350981]]


#Problem Statement2:Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.
 Hint:You can use isdigit(),islower(), and isupper() function.
Input: Original Array: ['Python' 'PHP' 'JS' 'Examples' 'html5' '5']
Output: Digits only = [False False False False False  True]
        Lower cases only = [False False False False  True False]
        Upper cases only = [False  True  True False False False]


In [30]:
import numpy as np
x=np.array(['Python','PHP','JS','Examples','html','5'])
print("Original array: ")
print(x)
s1=np.char.isdigit(x)
print("Digits only:",s1)
s2=np.char.islower(x)
print("Lower cases only: ",s2)
s3=np.char.isupper(x)
print("Upper case only: ",s3)

Original array: 
['Python' 'PHP' 'JS' 'Examples' 'html' '5']
Digits only: [False False False False False  True]
Lower cases only:  [False False False False  True False]
Upper case only:  [False  True  True False False False]


#Problem Statement3:Write a program thatreads two space-separated positive integers X and Y as input and perform the following tasks:
Tasks to be performed:
1.Create a list (lst1) starting at one (1) with 16 elements at a step of X
2.Create a list (lst2) starting at one (1) with 16 elements at a step of Y
3.Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4.Reshape both the NumPy arrays to (4,4)
5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)
6.Print all the elements of np3 in a single dimension list like the format as shown below:
a.[n0 n1 n2 n3 n4 n5 n6 n7 n8]

In [75]:
import numpy as np

In [79]:
#step1:Create a list (lst1) starting at one (1) with 16 elements at a step of X
x=int(input())
stop1=(16*x)+1
lst1=np.arange(1,stop1,x)
print("lst1",lst1)



7
lst1 [  1   8  15  22  29  36  43  50  57  64  71  78  85  92  99 106]


In [80]:
#step2:Create a list (lst2) starting at one (1) with 16 elements at a step of Y
y=int(input())
stop2=(16*y)+1
lst2=np.arange(1,stop2,y)
print("lst2: ",lst2)


9
lst2:  [  1  10  19  28  37  46  55  64  73  82  91 100 109 118 127 136]


In [85]:
#step3:Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
#step4.Reshape both the NumPy arrays to (4,4)
np1=np.array(lst1).reshape(4,4)
np2=np.array(lst2).reshape(4,4)
print("np1:  \n",np1)
print("np2:  \n",np2)

np1:  
 [[  1   8  15  22]
 [ 29  36  43  50]
 [ 57  64  71  78]
 [ 85  92  99 106]]
np2:  
 [[  1  10  19  28]
 [ 37  46  55  64]
 [ 73  82  91 100]
 [109 118 127 136]]


In [87]:
#step5:5.Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)
np3=np1-np2
print("np3:  \n",np3)

np3:  
 [[  0  -2  -4  -6]
 [ -8 -10 -12 -14]
 [-16 -18 -20 -22]
 [-24 -26 -28 -30]]


In [94]:
#step6:6.Print all the elements of np3 in a single dimension 
np3=np3.reshape(1,16)
print(np3)

[[  0  -2  -4  -6  -8 -10 -12 -14 -16 -18 -20 -22 -24 -26 -28 -30]]


#Problem Statement4: Write a Python program thattakes two integer-NumPy arrays, P and Q of shape[3*3] and perform the following task:
Task to be performed:
Print the element-wise difference of the matrix Pand Q (P−Q).
P=[23,56,87,3,6,96,4,6,78]
Q=[12,34,54,7,2,54,6,2,78]

In [100]:
P=[23,56,87,3,6,96,4,6,78]
Q=[12,34,54,7,2,54,6,2,78]
P=np.array(P)
Q=np.array(Q)
P=P.reshape(3,3)
Q=Q.reshape(3,3)
print("P: \n",P)
print("Q: \n",Q)
print("diffrence of the matrix P&Q: \n",P-Q)

P: 
 [[23 56 87]
 [ 3  6 96]
 [ 4  6 78]]
Q: 
 [[12 34 54]
 [ 7  2 54]
 [ 6  2 78]]
diffrence of the matrix P&Q: 
 [[11 22 33]
 [-4  4 42]
 [-2  4  0]]
